### ISSUE TITLE
Error formatting blocks

### ISSUE THREAD

**Issue by enboig** [artagnon/vstwig#25]
This code example is not formatted correctly:
```twig
{% extends 'ap/base.html.twig' %}
{% block title %}
    title
{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('app.css') }}">
    {% endblock %}    
```

**Comment by anarchist912** [comment]
@enboig Have you tried adding a slash before the closing > of the link tag? On my side formatting works, also the slash is removed in the rendered HTML.

**Comment by enboig** [comment]
Adding a slash _solves_ the problem. I assumed it was not needed for selclosed tags.
